### ISSUE TITLE
the thresholds

### ISSUE THREAD

**Issue by hsl20130659** [umang-singhal/pydom#1]
tks for your graeat work , recently I find this paper ,and found that you have recurrenced it ! But I have some confusements:
def get_sharpness(self, img, width=2, sharpness_threshold=2, sharpness_threshold=2, debug=False):

width=2,sharpness_threshold=2,sharpness_threshold=2, how do you define these  3 variables ?

**Comment by hsl20130659** [comment]
tks for your great work , recently I find this paper ,and found that you have recurrenced it ! But I have some confusements:
def get_sharpness(self, img, width=2, sharpness_threshold=2, sharpness_threshold=2, debug=False):

width=2,sharpness_threshold=2,sharpness_threshold=2, how do you define these 3 variables threshold?

**Comment by umang-singhal** [comment]
@hsl20130659 glad you find it useful.
Actually, the three variables are: width, edge_threshold, and sharpness_threshold
1. Here width is used for the line width and should be set according to the font and boldness of text you expect in your images. (refer to paper for window size `(2*w+1)`,  w = width).
2. edge threshold is used as is defined in the paper, which helps to identify if a pixel is edge pixel or not.
3. sharpness_threshold defines if the pixel is sharp or not and has to be decided as per the test images. Generally, the sharp pixels would have values above 2.5 or so. However, you are free to test it on your images and check if it proves to give good quality scores in your application.

**Comment by umang-singhal** [comment]
I hope your question was answered. I'm closing issue now, but if need be, please continue on the thread.
